Fix random build failure in swatch-common-panache
Some CI jobs are randomly failing due to:

```
Execution failed for task ':swatch-common-panache:quarkusAppPartsBuild'.
> There was a failure while executing work items
   > A failure occurred while executing io.quarkus.gradle.tasks.worker.BuildWorker
      > Configuration validation failed:
        	java.util.NoSuchElementException: SRCFG00011: Could not expand value platform.quarkus.native.builder-image in property quarkus.native.builder-image
```

These changes try to fix these failures.