Test removal of dependsOn testCodeCoverageReport task
This is a known issue about quarkus not working well with Gradle

Local workaround is

First build the sources
`./gradlew clean build -x test`

Then run the tests: `./gradlew test`

But we need to get around this issue in CI pipeline

```
Execution failed for task ':swatch-common-panache:quarkusAppPartsBuild'.

> There was a failure while executing work items

   > A failure occurred while executing io.quarkus.gradle.tasks.worker.BuildWorker

      > Configuration validation failed:

        	java.util.NoSuchElementException: SRCFG00011: Could not expand value platform.quarkus.native.builder-image in property quarkus.native.builder-image
```