Resolve OOM issue with archiving junit tests step in Jenkins job
Last step of the Jenkins pipeline is consistently failing because of this.

```
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.lang.StringUTF16.newBytesFor(Unknown Source)
	at java.base/java.lang.AbstractStringBuilder.inflate(Unknown Source)
	at java.base/java.lang.AbstractStringBuilder.putStringAt(Unknown Source)
	at java.base/java.lang.AbstractStringBuilder.putStringAt(Unknown Source)
```