Add user service env vars to marketplace-worker
https://issues.redhat.com/browse/ENT-3890

Otherwise, the defaults of localhost were being used resulting in errors
occur like:

```
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to localhost:443 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused) at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:156)
org.springframework.kafka.listener.ListenerExecutionFailedException: Listener method 'public void org.candlepin.subscriptions.marketplace.MarketplaceWorker.receive(org.candlepin.subscriptions.json.TallySummary)' threw exception; nested exception is javax.ws.rs.ProcessingException: RESTEASY004655: Unable to invoke request; nested exception is javax.ws.rs.ProcessingException: RESTEASY004655: Unable to invoke request
```

Testing
-------

1. Login to the CI environment via `oc`.
2. Use the internal ci deploy script as:

```
RHSM_SUBSCRIPTIONS_BRANCH=khowell/ent-3890-user-service-marketplace-worker ./deploy.sh
```