Reverting because it breaks the promql generator in swatchdog
A corresponding update to https://github.com/RedHatInsights/swatchdog needs to happen for us to change from a .yaml file

```
poetry run swatchdog prometheus promql --source ~/code/rhsm-subscriptions/swatch-metrics/src/main/resources/application.yaml --product-config-dir ~/code/rhsm-subscriptions/swatch-product-configuration/src/main/resources/subscription_configs --product rhacs --org 17771473
```

```
ScannerError: while scanning a directive
  in "/home/lburnett/code/rhsm-subscriptions/swatch-metrics/src/main/resources/application.properties", line 22, column 1
expected alphabetic or numeric character, but found '.'
  in "/home/lburnett/code/rhsm-subscriptions/swatch-metrics/src/main/resources/application.properties", line 22, column 5
```