swatch-core: add bunch of things to swatch-core
- Add db models to swatch-core
- Add shared exceptions to swatch-core
- Add task framework to swatch-core
- Add security config to swatch-core
- Fix issues with conflicting/missing task queue beans
- Move ApplicationClock to swatch-core and make it a component
- Refactor classes to use SecurityProperties
- Import core application yaml in root project
- Add swatch-core-test project: common test fixtures
- Make some ResourceUtils methods public (see note)
- Move kafka and dev-mode properties to swatch-core
- Update Jenkinsfile to gather test results for multiple projects
- Move test profile configs to swatch-core-test
- Remove unused getIdentityHeader method

NOTE: ResourceUtils methods made public:

So that they are exposed for use in the swatch-core jar.

Otherwise we get errors like:

```
2021-07-23 17:32:15,016 [thread=http-nio-8080-exec-6] [ERROR] [org.candlepin.subscriptions.exception.mapper.BaseExceptionMapper] [Account: account123, Owner: org123]- SUBSCRIPTIONS1000: An internal server error has occurred. Check the server logs for further details.
java.lang.IllegalAccessError: class org.candlepin.subscriptions.resource.OptInResource tried to access method 'java.lang.String org.candlepin.subscriptions.resource.ResourceUtils.getAccountNumber()' (org.candlepin.subscriptions.resource.OptInResource is in unnamed module of loader org.springframework.boot.devtools.restart.classloader.RestartClassLoader @7e9d6a15; org.candlepin.subscriptions.resource.ResourceUtils is in unnamed module of loader 'app')
```

Co-authored-by: Lindsey Burnett <lburnett@redhat.com>