Limit test artifact size by logging only failed and skipped tests
```
 2025-03-25 23:51:23 +0000 - publish -  INFO - Publishing failure results for commit 70d9e633078416fccacddad2aee4eeb9e3e88b30
2025-03-25 23:51:25 +0000 - publish -  INFO - Created check https://github.com/RedHatInsights/rhsm-subscriptions/runs/39408917732
2025-03-25 23:51:25 +0000 - publish -  INFO - Created job summary
2025-03-25 23:51:25 +0000 - publish -  INFO - Commenting on pull requests disabled
Error: lxml.etree.XMLSyntaxError: Memory allocation failed : Huge input lookup, line 39061, column 620
Error: Error processing result file: Memory allocation failed : Huge input lookup, line 39061, column 620 (TEST-org.candlepin.subscriptions.tally.export.InstancesDataExporterServiceTest.xml, line 39061)
```