podman_run.sh: s/-t/--time/
Current build_deploy.sh fails with

```
Error: unknown shorthand flag: 't' in -t
```

Hoping that changing to `--time` will address, and if not, we'll at
least get the podman version output for reference.