Make instance_id not null; populate from inventory_id when appropriate
Prior to this change, Account failed to load when existing records with
null instance_id are present, with an error:
`org.hibernate.HibernateException: null index column for collection`

There are a few changes related:

1) Update existing data by setting the value of `instance_id`
   to inventory_id for existing records (those with
   `instance_type='HBI_HOST'`).
2) Add a not null constraint to prevent future bad data.
3) Adjust Host so that when populating from inventory records,
   `instance_id` is populated.

Testing
-------
On `develop`, (*not* this branch), insert some mock hosts:

```
bin/insert-mock-hosts --num-physical 4
```

Insert some events:

```sql
insert into events(id, account_number, timestamp, data) values ('033a45b7-e8c4-440a-b0bb-76c3f3f67d85','account123', '2021-01-01T00:00Z', '{"account_number":"account123","timestamp":"2021-01-01T00:00:00Z","event_id":"033a45b7-e8c4-440a-b0bb-76c3f3f67d85","service_type":"OpenShift Cluster","instance_id":"4e8534b5-42b5-4f00-9969-29046e2b1986","measurements": [{"uom":"Cores","value":4.0}]}');
insert into events(id, account_number, timestamp, data) values ('a66ac2a1-17c0-4bc3-bc29-0430953d626c','account123', '2021-01-01T02:00Z', '{"account_number":"account123","timestamp":"2021-01-01T01:00:00Z","event_id":"a66ac2a1-17c0-4bc3-bc29-0430953d626c","service_type":"OpenShift Cluster","instance_id":"4e8534b5-42b5-4f00-9969-29046e2b1986","measurements": [{"uom":"Cores","value":2.0}]}');
insert into events(id, account_number, timestamp, data) values ('fad48795-ae0a-4674-b864-822ddfb799d0','account123', '2021-01-01T03:00Z', '{"account_number":"account123","timestamp":"2021-01-01T02:00:00Z","event_id":"fad48795-ae0a-4674-b864-822ddfb799d0","service_type":"OpenShift Cluster","instance_id":"4e8534b5-42b5-4f00-9969-29046e2b1986","measurements": [{"uom":"Cores","value":4.0}]}');
```

Run the service:

```
./gradlew bootRun
```

Trigger an hourly tally:

```
curl 'http://localhost:8080/actuator/hawtio/jolokia/' -H 'Content-Type: application/json' -d '{"type":"exec","mbean":"org.candlepin.subscriptions.jmx:name=tallyJmxBean,type=TallyJmxBean","operation":"tallyAccountByHourly(java.lang.String,java.lang.String,java.lang.String)","arguments":["account123","2021-01-01T00:00:00Z","2021-01-01T23:59:59.999Z"]}'
```

Observe:

```
[ERROR] [org.candlepin.subscriptions.tally.TallySnapshotController] - Could not collect existing usage snapshots for account account123
org.springframework.orm.jpa.JpaSystemException: null index column for collection: org.candlepin.subscriptions.db.model.Account.serviceInstances; nested exception is org.hibernate.HibernateException: null index column for collection: org.candlepin.subscriptions.db.model.Account.serviceInstances
```

Now, checkout this branch, and restart the service. Without clearing
data, re-run the hourly tally, and observe that it completes without
error.