Fix TagProfile loading from classpath
Using `ResourceUtils.getFile()` for a file that is on the classpath, and
not the filesystem won't work. Doh!

Testing
-------
`./gradlew assemble` from `develop`, run `java -jar
build/libs/rhsm-subscriptions-1.0.53-SNAPSHOT.jar`, observe message w/

```
java.io.FileNotFoundException: class path resource [tag_profile.yaml] cannot be resolved to absolute file path because it does not reside in the file system: jar:file:/deployments/rhsm-subscriptions-1.0.53-SNAPSHOT.jar!/BOOT-INF/classes!/tag_profile.yaml
```

Repeat steps with this branch, observe that the app starts without
errors.