Simplify clowder loading
Only use the `ACG_CONFIG` env var.

With the modifications, `ACG_CONFIG` is exclusively used to determine
whether to attempt to load clowder config, and it's a fatal error
to fail config reading if `ACG_CONFIG` is defined.

This is more consistent with what's described at
https://github.com/RedHatInsights/clowder/blob/4908ea02a4b622a4f94324f17e0ad728d77f377d/docs/antora/modules/migration/pages/migration.adoc#code-changes-to-consume-configuration
as well as what's implemented in the python client:
https://github.com/RedHatInsights/app-common-python/blob/48b27daf6d280650681014ce137eab1a0e910a44/app_common_python/__init__.py#L17-L18

Testing
-------

1. Run the app normally: `./gradlew :bootRun`

2. Run the app with a missing clowder config:

```
ACG_CONFIG=/tmp/idontexist ./gradlew :bootRun
```

```
java.lang.IllegalStateException: Could not read clowder config
  [...]
Caused by: java.io.FileNotFoundException: /tmp/idontexist (No such file or directory)
```

3. Run the app with a present clowder config:

```
ACG_CONFIG=$(pwd)/swatch-core/src/test/resources/test-clowder-config.json ./gradlew :bootRun
```

Startup will fail with

```
No resolvable bootstrap urls given in bootstrap.servers
```

(This is set to env-rhsm-kafka.rhsm.svc:29092 in the test config).