Make JPA converters handle _ANY value
This was causing issues like the following in rhsm-ci:

```
java.lang.IllegalStateException: Duplicate key TallySnapshot{id=REDACTED, snapshotDate=2020-05-01T00:00Z, granularity=MONTHLY, accountNumber=REDACTED, productId='RHEL', serviceLevel='UNSPECIFIED', usage='UNSPECIFIED'}
```